# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dialrs_wrappers", use_symbols = TRUE, package_name = "dialrs")

#' @docType package
#' @usage NULL
#' @useDynLib dialrs, .registration = TRUE
NULL

is_valid_rs <- function(phone, country) .Call(wrap__is_valid_rs, phone, country)

phone_types_rs <- function(phone, country) .Call(wrap__phone_types_rs, phone, country)

parse_phone_rs_international <- function(phone, country) .Call(wrap__parse_phone_rs_international, phone, country)

parse_phone_rs_national <- function(phone, country) .Call(wrap__parse_phone_rs_national, phone, country)

parse_phone_rs_rfc3966 <- function(phone, country) .Call(wrap__parse_phone_rs_rfc3966, phone, country)

parse_phone_rs_e164 <- function(phone, country) .Call(wrap__parse_phone_rs_e164, phone, country)

phone_country_codes_rs <- function(phone) .Call(wrap__phone_country_codes_rs, phone)

#' Print Rust internal phonenumber for debugging purposes
#' @param input character. a phone number to parse
#' @param country_code character. CLDR code
#' @return nothing just used for side effects
#' @export
phone_debug_print <- function(input, country) invisible(.Call(wrap__phone_debug_print, input, country))


# nolint end
