# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dialrs_wrappers", use_symbols = TRUE, package_name = "dialrs")

#' @docType package
#' @usage NULL
#' @useDynLib dialrs, .registration = TRUE
NULL

#' @export
is_valid <- function(input) .Call(wrap__is_valid, input)

#' @export
parse_phone_print <- function(input) invisible(.Call(wrap__parse_phone_print, input))

#' @export
phone_to_r <- function(input, country) .Call(wrap__phone_to_r, input, country)

#' @export
phones_to_r <- function(inputs) .Call(wrap__phones_to_r, inputs)

#' @export
phone_types <- function(inputs) .Call(wrap__phone_types, inputs)


# nolint end
