# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dialrs_wrappers", use_symbols = TRUE, package_name = "dialrs")

#' @docType package
#' @usage NULL
#' @useDynLib dialrs, .registration = TRUE
NULL

#' @export
is_valid <- function(input) .Call(wrap__is_valid, input)

#' @export
parse_phone_print <- function(input) invisible(.Call(wrap__parse_phone_print, input))

#' @export
parse_phone_r <- function(input) .Call(wrap__parse_phone_r, input)


# nolint end
